name: pharmacy_app
description: A new Flutter application for medicine delivery.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: 0.1.2
  google_fonts: 1.1.0
  tuple: 1.0.3
  fluttertoast: 3.1.3
  shared_preferences: 0.5.6
  image: 2.1.12
  http: 0.12.2
  multi_image_picker: 4.7.14
  permission_handler: 5.0.1
  table_calendar: 2.2.2
  jiffy: 3.0.1
  image_picker: 0.6.7
  country_pickers: 1.1.0
  launch_review: 2.0.0
  cached_network_image: 2.0.0-rc
  url_launcher: 5.6.0
  package_info: 0.4.3
  soundpool: 1.1.2
  carousel_slider: 2.3.1


  geocoder: 0.2.1
  location: 3.0.2
  google_maps_flutter: 1.0.2
  geolocator: 5.3.2+2

  firebase_core: 0.7.0
  firebase_storage: 7.0.0
  firebase_auth: 0.20.0+1
  firebase_analytics: 5.0.1
  firebase_messaging: ^8.0.0-dev.14
  flutter_local_notifications: 3.0.3
  intl: 0.16.1


  path_provider: 1.6.5
  esc_pos_utils: 1.0.0
  esc_pos_printer: 4.0.3
  wifi: 0.1.5
  ping_discover_network: 0.2.0+1
  charset_converter: 1.0.3
  pdf: 1.12.0
  dolumns: 1.0.1+1
  printing: 3.7.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "0.7.3"

flutter_icons:
  ios: true
  android: true
  image_path_ios: "assets/images/logo_aamarpharma.jpg"
  image_path_android: "assets/images/logo_aamarpharma.jpg"
  # flutter pub get; flutter pub run flutter_launcher_icons:main

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  fonts:
    - family: solaiman
      fonts:
        - asset: assets/fonts/solaiman.ttf


  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
    - assets/images/
    - assets/sounds/

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
